parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: '5432'
    database_name: postgres
    database_user: postgres
    database_password: postgres
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8b6f7461e054875166cfb9273d0bf509ee76c63b
    database_path: null
